var $jscomp={scope:{}};$jscomp.defineProperty="function"==typeof Object.defineProperties?Object.defineProperty:function(a,c,b){if(b.get||b.set)throw new TypeError("ES3 does not support getters and setters.");a!=Array.prototype&&a!=Object.prototype&&(a[c]=b.value)};$jscomp.getGlobal=function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global&&null!=global?global:a};$jscomp.global=$jscomp.getGlobal(this);
$jscomp.polyfill=function(a,c,b,d){if(c){b=$jscomp.global;a=a.split(".");for(d=0;d<a.length-1;d++){var e=a[d];e in b||(b[e]={});b=b[e]}a=a[a.length-1];d=b[a];c=c(d);c!=d&&null!=c&&$jscomp.defineProperty(b,a,{configurable:!0,writable:!0,value:c})}};$jscomp.polyfill("Array.prototype.fill",function(a){return a?a:function(a,b,d){var c=this.length||0;0>b&&(b=Math.max(0,c+b));if(null==d||d>c)d=c;d=Number(d);0>d&&(d=Math.max(0,c+d));for(b=Number(b||0);b<d;b++)this[b]=a;return this}},"es6-impl","es3");
var dataMachine=new DataMachine,tblChartData_1=$("#tblChartData_1").DataTable({dom:"Bfrtip",buttons:[{extend:"copy",text:"Kopieren",exportOptions:{columns:":visible"}},{extend:"csv",text:"CSV-Export",exportOptions:{columns:":visible"}},{extend:"print",text:"Drucken",exportOptions:{columns:":visible"}}],pageLength:15,bAutoWidth:!1,colReorder:!0,columnDefs:[{width:"33%",targets:0},{width:"33%",targets:1},{width:"33%",targets:2}]});
tblChartData_2=$("#tblChartData_2").DataTable({dom:"Bfrtip",buttons:[{extend:"copy",text:"Kopieren",exportOptions:{columns:":visible"}},{extend:"csv",text:"CSV-Export",exportOptions:{columns:":visible"}},{extend:"print",text:"Drucken",exportOptions:{columns:":visible"}}],pageLength:15,bAutoWidth:!1,colReorder:!0,columnDefs:[{width:"33%",targets:0},{width:"33%",targets:1},{width:"33%",targets:2}]});
tblChartData_3=$("#tblChartData_3").DataTable({dom:"Bfrtip",buttons:[{extend:"copy",text:"Kopieren",exportOptions:{columns:":visible"}},{extend:"csv",text:"CSV-Export",exportOptions:{columns:":visible"}},{extend:"print",text:"Drucken",exportOptions:{columns:":visible"}}],pageLength:15,bAutoWidth:!1,colReorder:!0,columnDefs:[{width:"33%",targets:0},{width:"33%",targets:1},{width:"33%",targets:2}]});year=sessionStorage.getItem("year");monthArr="Januar Februar M\u00e4rz April Mai Juni Juli August September Oktober November Dezember".split(" ");
month=sessionStorage.getItem("month");nameDB=sessionStorage.getItem("nameDB");chartType=sessionStorage.getItem("chartType");displayMean=sessionStorage.getItem("displayMean");nameMst_1=sessionStorage.getItem("nameMst_1");nameMst_2=sessionStorage.getItem("nameMst_2");nameMst_3=sessionStorage.getItem("nameMst_3");queryString_1=sessionStorage.getItem("queryString_1");queryString_2=sessionStorage.getItem("queryString_2");queryString_3=sessionStorage.getItem("queryString_3");
headerDiagramm="Energieverbrauch "+monthArr[Number(month)-1]+" "+year;csOptions=null;
var notes=[],msts=[],note=function(a){return function(c){return function(b){return function(d){return"<div class='bem'><label style='margin-right:10px;'>"+a+" </label><label style='margin-right:10px;color:"+b+"'>"+c+" </label><label>"+d+" </label></div>"}}}},appendTo=function(a){return function(c){return $(a).append(c)}},formatDate=function(a){return 1===a.length?"0"+a:a},updateNotes=function(a){return function(c){return function(b){return $.ajax({type:"POST",async:!0,url:"php/readNote.php",data:{ins:"read",
nameDB:nameDB,mstID:a,type:"month"},success:function(a){insJson=JSON.parse(a);console.log(insJson);0<insJson.length&&insJson.filter(function(a){return a.ident.split("/")[0]===year&&a.ident.split("/")[1]===month}).forEach(function(a){appendTo("#bemList")(note(a.ident)(c)(b)(a.bemerkung));notes.push([a.ident,c,a.mst_ID,b,a.bemerkung])})}})}}};
csOptions="line"==chartType?{tooltip:{visible:!0},border:{width:2},marker:{shape:"circle",size:{height:10,width:10},visible:!0}}:{tooltip:{visible:!0},border:{width:2},marker:{dataLabel:{visible:!0}}};$("#btnNoteAbbr").click(function(){$("#notePopup").dialog("close")});
$("#btnNoteOk").click(function(){$("#notePopup").dialog("close");$.ajax({type:"POST",async:!0,url:"php/saveNote.php",data:{ins:"test",nameDB:nameDB,ident:$("#identNote").val(),mstID:$("#mstIDNote").val()},success:function(a){insJson=JSON.parse(a);ins=0===insJson.length?"new":"save";$.ajax({type:"POST",async:!0,url:"php/saveNote.php",data:{ins:ins,nameDB:nameDB,type:"month",mstID:$("#mstIDNote").val(),ident:$("#identNote").val(),bemerkung:$("#bemerkungNote").val()},success:function(a){alert("Daten gespeichert!");
appendTo("#bemList")(note($("#identNote").val())($("#mstNote").val())("black")($("#bemerkungNote").val()));$("#identNote").val("");$("#mstIDNote").val("");$("#mstNote").val("");$("#bemerkungNote").val("")}})}})});
$("#btnSaveOk").click(function(){$("#savePopup").dialog("close");var a=$("#container").ejChart("instance");$.ajax({type:"POST",async:!0,url:"php/saveDiag.php",data:{ins:"saveDiag",nameDB:nameDB,name:headerDiagramm,typ:"month",jsonDiag:JSON.stringify(a.model.series.map(function(a){return a.dataSource}))},success:function(a){alert("Daten gespeichert!")}})});
$("#diagSpeichern").click(function(){$("#savePopup").dialog({resize:"auto",show:{effect:"fade",duration:500},hide:{effect:"fade",duration:500},width:425,height:250})});
$("#container").ejChart({pointRegionClick:function(a){console.log(a);console.log("NrPoint: "+a.data.region.Region.PointIndex);console.log("Dataseries: "+a.data.region.SeriesIndex);$("#notePopup").dialog({resize:"auto",show:{effect:"fade",duration:500},hide:{effect:"fade",duration:500},width:425,height:295});$("#identNote").val(year+"/"+month+"/"+formatDate(String(a.data.region.Region.PointIndex+1)));$("#mstIDNote").val(msts[a.data.region.SeriesIndex][0]);$("#mstNote").val(msts[a.data.region.SeriesIndex][1]);
a=notes.filter(function(a){return a[0]===$("#identNote").val()&&a[2]==$("#mstIDNote").val()});$("#bemerkungNote").val(1===a.length?a[0][4]:"");console.log("notes");console.log(notes)},legend:{position:"top"},primaryXAxis:{title:{text:"Tag"}},primaryYAxis:{title:{text:"Verbrauch[kWh]"}},commonSeriesOptions:csOptions,series:[]});$("h3").text(headerDiagramm);
""!=queryString_1&&""!=queryString_2&&""!=queryString_3?(firstQuery(),secondQuery(),thirdQuery()):""!=queryString_1&&""!=queryString_2?(firstQuery(),secondQuery()):""!=queryString_1?firstQuery():console.log("There're no query data!!");
function firstQuery(){dataMachine.runQuery("read",nameDB,queryString_1).then(JSON.parse).then(function(a){var c=[],b=0;a="001_heco"==nameDB||"002_badber"==nameDB||"003_tauchzor"==nameDB?new DataTranslator(TranslationType.ENERGY_DATA_02,a):new DataTranslator(TranslationType.ENERGY_DATA_01,a);console.log(c);a.sumDays(year,month);c=a.translate(4);for(a=0;a<c.length;a++)tblChartData_1.row.add([c[1].name,c[a].x+"."+month+"."+year,c[a].y]).draw(),b+=c[a].y;$("#consumption-month_1").text(Math.round(b)+" kWh");
colorMst=updateChart(c,nameMst_1);msts.push([sessionStorage.getItem("mstID_1"),nameMst_1]);updateNotes(sessionStorage.getItem("mstID_1"))(sessionStorage.getItem("nameMst_1"))(colorMst)})}
function secondQuery(){dataMachine.runQuery("read",nameDB,queryString_2).then(JSON.parse).then(function(a){var c=0;a="001_heco"==nameDB||"002_badber"==nameDB||"003_tauchzor"==nameDB?new DataTranslator(TranslationType.ENERGY_DATA_02,a):new DataTranslator(TranslationType.ENERGY_DATA_01,a);a.sumDays(year,month);a=a.translate(4);for(var b=0;b<a.length;b++)tblChartData_2.row.add([a[1].name,a[b].x+"."+month+"."+year,a[b].y]).draw(),c+=a[b].y;$("#consumption-month_2").text(Math.round(c)+" kWh");colorMst2=
updateChart(a,nameMst_2);msts.push([sessionStorage.getItem("mstID_2"),nameMst_2]);updateNotes(sessionStorage.getItem("mstID_2"))(sessionStorage.getItem("nameMst_2"))(colorMst2)})}
function thirdQuery(){dataMachine.runQuery("read",nameDB,queryString_3).then(JSON.parse).then(function(a){var c=0;a="001_heco"==nameDB||"002_badber"==nameDB||"003_tauchzor"==nameDB?new DataTranslator(TranslationType.ENERGY_DATA_02,a):new DataTranslator(TranslationType.ENERGY_DATA_01,a);a.sumDays(year,month);a=a.translate(4);for(var b=0;b<a.length;b++)tblChartData_3.row.add([a[1].name,a[b].x+"."+month+"."+year,a[b].y]).draw(),c+=a[b].y;$("#consumption-month_3").text(Math.round(c)+" kWh");colorMst3=
updateChart(a,nameMst_3);msts.push([sessionStorage.getItem("mstID_3"),nameMst_3]);updateNotes(sessionStorage.getItem("mstID_3"))(sessionStorage.getItem("nameMst_3"))(colorMst3)})}function updateChart(a,c){var b=$("#container").ejChart("instance"),d=b.model.series.length;b.model.series.push({type:chartType,name:c,dataSource:a,xName:"x",yName:"y"});b.redraw();return b.model.series[d].fill};
