var $jscomp={scope:{},checkStringArgs:function(c,e,f){if(null==c)throw new TypeError("The 'this' value for String.prototype."+f+" must not be null or undefined");if(e instanceof RegExp)throw new TypeError("First argument to String.prototype."+f+" must not be a regular expression");return c+""}};
$jscomp.defineProperty="function"==typeof Object.defineProperties?Object.defineProperty:function(c,e,f){if(f.get||f.set)throw new TypeError("ES3 does not support getters and setters.");c!=Array.prototype&&c!=Object.prototype&&(c[e]=f.value)};$jscomp.getGlobal=function(c){return"undefined"!=typeof window&&window===c?c:"undefined"!=typeof global&&null!=global?global:c};$jscomp.global=$jscomp.getGlobal(this);
$jscomp.polyfill=function(c,e,f,g){if(e){f=$jscomp.global;c=c.split(".");for(g=0;g<c.length-1;g++){var b=c[g];b in f||(f[b]={});f=f[b]}c=c[c.length-1];g=f[c];e=e(g);e!=g&&null!=e&&$jscomp.defineProperty(f,c,{configurable:!0,writable:!0,value:e})}};
$jscomp.polyfill("String.prototype.repeat",function(c){return c?c:function(c){var f=$jscomp.checkStringArgs(this,null,"repeat");if(0>c||1342177279<c)throw new RangeError("Invalid count value");c|=0;for(var e="";c;)if(c&1&&(e+=f),c>>>=1)f+=f;return e}},"es6-impl","es3");
var scpCore=Object.freeze(new function(){var c=this,e=function(b){switch(typeof a){case "number":b=b===Math.round(b)?"integer":"float";break;case "object":b=b instanceof Array?"array":b instanceof Function?"function":"record";break;default:b=typeof b}return b},f=Object.freeze({isString:function(b){return"string"===e(b)},isBool:function(b){return"boolean"===e(b)},isInt:function(b){return"integer"===e(b)},isFloat:function(b){return"float"===e(b)},isArray:function(b){return"array"===e(b)},isRecord:function(b){return"record"===
e(b)},isFunction:function(b){return"function"===e(b)}}),g=f.isString;this.type=f;this.splt=this.split_=function(b){return function(d){return g(b)&&g(d)?d.split(b):console.error("scpCore.split_ : invalid datatypes ! \nEXPECTED 'string => string', \nACTUAL '"+e(b)+" => "+e(d)+"'")}};this.jn=this.join_=function(b){return function(d){return d.join(b)}};this.len=this.length_=function(b){return b.length};this.trim_=function(b){return b.trim()};this.trm=function(b){return b.trim()};this.id=function(b){return b};
this.flip=function(b){return function(d){return function(c){return b(c)(d)}}};this.first=function(b){return function(d){return b}};this.second=function(b){return function(b){return b}};this.apply=function(b){return function(d){return b(d)}};this.not=this.first?this.second:this.first;this.equal=function(b){return function(d){return b===d}};this.unequal=function(b){return function(d){return c.not(c.equal(b)(d))}};this.greater=function(b){return function(d){return b>d}};this.greaterZero=this.flip(this.greater)(0);
this.greaterOne=this.flip(this.greater)(1);this.smaller=this.flip(this.greater);this.applyRv=this.flip(this.apply);this.compose=function(b){return function(d){return function(c){return b(d(c))}}};this.singleton=function(b){return[].concat([b])};this.isSingleton=function(b){return equal(b.length)(1)};this.array=function(b){return function(d){return function(h){h=void 0===h?this.singleton(d):h;return c.greater(b)(1)?h.concat(c.array(b-1)(d)(c.singleton(d))):h}}};this.head=function(b){return b[0]};this.arrayFrom=
function(b){return b.split(",").map(c.trim_)};this.isDefined=function(b){return c.not(c.equal(b,null)||c.equal(b,void 0)||c.equal(b,""))};this.tail=function(b){return b.slice(1)};this.last=function(b){return b[b.length-1]};this.flatten=function(b){return b.reduce(function(b,c){return b.concat(c)},[])};this.altFuse=function(b){return function(d){return c.flatten(b.map(function(b,c){return c<=d.length-1?[b,d[c]]:b}))}};this.incr=function(b){return b+1};this.decr=function(b){return b-1};this.sum=function(b,
d,c){return(void 0===c?0:c)?Number(b)+Number(d):b+d};this.subtract=function(b,d,c){return(void 0===c?0:c)?Number(b)-Number(d):b-d};this.devide=function(b,c){return b/c};this.multiply=function(b,c){return b*c};this.round=function(b){return function(c){return Math.round(b*Math.pow(10,c))/Math.pow(10,c)}};this.roundWithZeros=function(b){return function(d){return 2===String(c.round(b)(d)).split(".").length?c.round(b)(d)+"0".repeat(c.subtract(d,String(c.round(b)(d)).split(".")[1].length)):b}};this.doOperation=
function(b){return function(d){return function(e){var f=Number(String(d).replace(",",".")),h=Number(String(e).replace(",","."));switch(b){case "(":return c.opnPths(d,e);case ")":return c.clsPths(d,e);case "/":return c.devide(f,h);case "+":return c.sum(f,h);case "*":return c.multiply(f,h);case "-":return c.subtract(f,h);default:alert("doOperation(a, b) : \nAn invalid operator was found!")}}}};this.average=function(b){return b.reduce(sum)/b.length};this.exclude=function(b){return function(d){return 0<
b.filter(c.equal(d)).length}};this.get=function(b){return function(c){return c.split(" ").filter(b)}};this.toObject=function(b){return function(d){return replace(b)(["{","}"]).split(",").map(split_(":")).forEach(function(b){return c.set(c.makeProperty(d)(b[0])(b[1]))})}};this.emptyString=function(b){return c.equal(b)("")};this.replace=function(b){return function(c,e){e=void 0===e?"":e;return c.reduce(function(c,d){c=void 0===c?b:c;return c.replace(d,e)})}};this.makeRecord=function(b){return Object(b)};
this.addField=function(b){return function(c){return function(d){return b[c]=d}}};this.field=function(b){return function(c){return b[c]}};this.decode=this.id;this.json=function(b){try{JSON.parse(b)}catch(d){return!1}return JSON.parse(b)};this.freeze=function(b){return Object.freeze(b)};this.exists=function(b){return function(c){return b.hasOwnProperty(c)}};this.deepFreeze=function(b){c.freeze(b);Object.getOwnPropertyNames(b).forEach(function(d){!exists(b)(d)||null===b[d]||"object"!==typeof b[d]&&"function"!==
typeof b[d]||Object.isFrozen(b[d])||c.deepFreeze(b[d])});return b};this.fetchPost=function(b){return function(c){return fetch(b,{method:"POST",body:c})}};this.fetchGet=function(b){return fetch(b,{method:"GET"})}}),$jscomp$destructuring$var1=scpCore,type=scpCore.type,split_=scpCore.split_,splt=scpCore.splt,join_=scpCore.join_,jn=scpCore.jn,length_=scpCore.length_,len=scpCore.len,trim_=scpCore.trim_,trm=scpCore.trm,id=scpCore.id,first=scpCore.first,second=scpCore.second,apply=scpCore.apply,not=scpCore.not,
flip=scpCore.flip,equal=scpCore.equal,unequal=scpCore.unequal,greater=scpCore.greater,greaterZero=scpCore.greaterZero,greaterOne=scpCore.greaterOne,smaller=scpCore.smaller,applyRv=scpCore.applyRv,compose=scpCore.compose,singleton=scpCore.singleton,isSingleton=scpCore.isSingleton,array=scpCore.array,head=scpCore.head,arrayFrom=scpCore.arrayFrom,isDefined=scpCore.isDefined,tail=scpCore.tail,last=scpCore.last,flatten=scpCore.flatten,altFuse=scpCore.altFuse,incr=scpCore.incr,decr=scpCore.decr,sum=scpCore.sum,
subtract=scpCore.subtract,devide=scpCore.devide,multiply=scpCore.multiply,round=scpCore.round,roundWithZeros=scpCore.roundWithZeros,doOperation=scpCore.doOperation,average=scpCore.average,exclude=scpCore.exclude,get=scpCore.get,toObject=scpCore.toObject,emptyString=scpCore.emptyString,replace=scpCore.replace,makeRecord=scpCore.makeRecord,addField=scpCore.addField,field=scpCore.field,decode=scpCore.decode,json=scpCore.json,freeze=scpCore.freeze,exists=scpCore.exists,deepFreeze=scpCore.deepFreeze;
