<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class MandantenSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //
        DB::table('mandanten')->insert([   
            ['datumAdm' => "2017-10-13", 'titelAdm' =>"", 'nameAdm' => "", 'vornameAdm' => "", 'emailAdm' => "", 'telefonAdm' => "", 'faxAdm' => "", 'mobiltelefonAdm' => "", 'benutzernameAdm' => "", 'nameMan' => "Mustermandant", 'holdingstruktur' => "0", 'liegenschaften' => "1", 'dbName' => "g000_demo", 'mehrbenutzer' => "0", 'betrGrp_ID' => 21, 'man_ID' => 1, 'notiz' => "" ],
            ['datumAdm' => "2017-04-07", 'titelAdm' =>"Herr", 'nameAdm' => "Beier", 'vornameAdm' => "Christian", 'emailAdm' => "christian.beier@heutecomp.de", 'telefonAdm' => "+49 (2195) 676775", 'faxAdm' => "+49 (2755) 888140", 'mobiltelefonAdm' => "", 'benutzernameAdm' => "C.Beier", 'nameMan' => "Heute + Comp", 'holdingstruktur' => "0", 'liegenschaften' => "0", 'dbName' => "g001_heco", 'mehrbenutzer' => "0", 'betrGrp_ID' => 21, 'man_ID' => 2, 'notiz' => "" ],
            ['datumAdm' => "2017-04-07", 'titelAdm' =>"Herr", 'nameAdm' => "Knebel", 'vornameAdm' => "Philipp", 'emailAdm' => "Philipp.Knebel@agrodur.de", 'telefonAdm' => "+ (2755) 888263", 'faxAdm' => "+49 (2755) 888199", 'mobiltelefonAdm' => "", 'benutzernameAdm' => "P.Knebel", 'nameMan' => "Agrodur Bad Berleburg", 'holdingstruktur' => "0", 'liegenschaften' => "1", 'dbName' => "g002_badber", 'mehrbenutzer' => "1", 'betrGrp_ID' => 21, 'man_ID' => 3, 'notiz' => "" ],
            ['datumAdm' => "2017-04-07", 'titelAdm' =>"Herr", 'nameAdm' => "Oelzner", 'vornameAdm' => "Uwe", 'emailAdm' => "oelzner@agrodur.de", 'telefonAdm' => "+49 (34441) 32316", 'faxAdm' => "+49 (34441) 32333", 'mobiltelefonAdm' => "", 'benutzernameAdm' => "U.Oelzner", 'nameMan' => "Agrodur Kunststofftechnik", 'holdingstruktur' => "0", 'liegenschaften' => "1", 'dbName' => "g003_tauchzor", 'mehrbenutzer' => "0", 'betrGrp_ID' => 21, 'man_ID' => 4, 'notiz' => "" ],
            ['datumAdm' => "2017-04-11", 'titelAdm' =>"Herr", 'nameAdm' => "Derichsweiler", 'vornameAdm' => "Thorsten", 'emailAdm' => "thorsten.derichsweiler@gmx.de", 'telefonAdm' => "+49 (2293) 90900", 'faxAdm' => "+49 (2293) 909038", 'mobiltelefonAdm' => "+49 (171) 5011879", 'benutzernameAdm' => "T.Derichsweiler", 'nameMan' => "Familie Derichsweiler", 'holdingstruktur' => "0", 'liegenschaften' => "0", 'dbName' => "g004_derhof", 'mehrbenutzer' => "0", 'betrGrp_ID' => 21, 'man_ID' => 5, 'notiz' => "" ],
            ['datumAdm' => "2017-04-13", 'titelAdm' =>"Herr" , 'nameAdm' => "Benjamins", 'vornameAdm' => "JÃ¶rg", 'emailAdm' => "benjamins@t-online.de", 'telefonAdm' => "+49 (2195) 91300", 'faxAdm' => "+49 (2195) 913030", 'mobiltelefonAdm' => "", 'benutzernameAdm' => "Benjamins", 'nameMan' => "Benjamins", 'holdingstruktur' => "1", 'liegenschaften' => "0", 'dbName' => "g005_sccben", 'mehrbenutzer' => "1", 'betrGrp_ID' => 21, 'man_ID' => 6, 'notiz' => "" ],
            ['datumAdm' => "2017-07-02", 'titelAdm' =>"Herr", 'nameAdm' => "Kranenberg", 'vornameAdm' => "Ansgar", 'emailAdm' => "Ansgar.Kranenberg@Raderplast.de", 'telefonAdm' => "+49 (2195) 917817", 'faxAdm' => "+49 (2195) 91720", 'mobiltelefonAdm' => "", 'benutzernameAdm' => "A-RPKI", 'nameMan' => "Raderplast", 'holdingstruktur' => "0", 'liegenschaften' => "1", 'dbName' => "g006_radpl", 'mehrbenutzer' => "1", 'betrGrp_ID' => 21, 'man_ID' => 7, 'notiz' => "" ],
            ['datumAdm' => "2017-08-04", 'titelAdm' =>"", 'nameAdm' => "", 'vornameAdm' => "", 'emailAdm' => "", 'telefonAdm' => "", 'faxAdm' => "", 'mobiltelefonAdm' => "", 'benutzernameAdm' => "Erben", 'nameMan' => "Linsen Druckcenter GmbH", 'holdingstruktur' => "0", 'liegenschaften' => "0", 'dbName' => "g007_linsdr", 'mehrbenutzer' => "0", 'betrGrp_ID' => 21, 'man_ID' => 8, 'notiz' => "" ],
            ['datumAdm' => "2017-09-06", 'titelAdm' =>"Herr", 'nameAdm' => "Wieland", 'vornameAdm' => "Adrian", 'emailAdm' => "info@energie-gipscomm.de", 'telefonAdm' => "02192 / 853712 ", 'faxAdm' => " 02192 / 853713", 'mobiltelefonAdm' => "0171 97 44 77 5", 'benutzernameAdm' => "D.Test", 'nameMan' => "Gipscomm Holding", 'holdingstruktur' => "1", 'liegenschaften' => "0", 'dbName' => "g008_gipshold", 'mehrbenutzer' => "1", 'betrGrp_ID' => 21, 'man_ID' => 9, 'notiz' => "" ],
            ['datumAdm' => "2017-09-06", 'titelAdm' =>"Hr", 'nameAdm' => "Linde", 'vornameAdm' => "Patric", 'emailAdm' => "", 'telefonAdm' => "", 'faxAdm' => "", 'mobiltelefonAdm' => "", 'benutzernameAdm' => "P.Linde", 'nameMan' => "AST", 'holdingstruktur' => "0", 'liegenschaften' => "1", 'dbName' => "g009_astall", 'mehrbenutzer' => "0", 'betrGrp_ID' => 21, 'man_ID' => 10, 'notiz' => "" ],
            ['datumAdm' => "2017-09-15", 'titelAdm' =>"Herr", 'nameAdm' => "Stahlschmidt", 'vornameAdm' => "Jörg", 'emailAdm' => "J.Stahlschmidt@HBS-Stahlschmidt.de", 'telefonAdm' => "", 'faxAdm' => "", 'mobiltelefonAdm' => "", 'benutzernameAdm' => "J.Stahlschmidt", 'nameMan' => "HBS-gipshold", 'holdingstruktur' => "0", 'liegenschaften' => "0", 'dbName' => "g008_gipshold", 'mehrbenutzer' => "0", 'betrGrp_ID' => 21, 'man_ID' => 14, 'notiz' => "" ],
            ['datumAdm' => "2017-09-15", 'titelAdm' =>"Herr", 'nameAdm' => "Stahlschmidt", 'vornameAdm' => "Jörg", 'emailAdm' => "J.Stahlschmidt@HBS-Stahlschmidt.de", 'telefonAdm' => "", 'faxAdm' => "", 'mobiltelefonAdm' => "", 'benutzernameAdm' => "J.Stahlschmidt", 'nameMan' => "HBS-Herholz-Tueren", 'holdingstruktur' => "0", 'liegenschaften' => "0", 'dbName' => "g010_hbsherholz", 'mehrbenutzer' => "0", 'betrGrp_ID' => 21, 'man_ID' => 15, 'notiz' => "" ],
            ['datumAdm' => "2017-11-10", 'titelAdm' =>"NULL", 'nameAdm' => "", 'vornameAdm' => "", 'emailAdm' => "", 'telefonAdm' => "", 'faxAdm' => "", 'mobiltelefonAdm' => "", 'benutzernameAdm' => "", 'nameMan' => "K.H.Schumacher", 'holdingstruktur' => "", 'liegenschaften' => "", 'dbName' => "g011_khschum", 'mehrbenutzer' => "", 'betrGrp_ID' => 21, 'man_ID' => 17, 'notiz' => "" ],
            ['datumAdm' => "2017-11-10", 'titelAdm' =>"NULL", 'nameAdm' => "", 'vornameAdm' => "", 'emailAdm' => "", 'telefonAdm' => "", 'faxAdm' => "", 'mobiltelefonAdm' => "", 'benutzernameAdm' => "", 'nameMan' => "Spies", 'holdingstruktur' => "", 'liegenschaften' => "", 'dbName' => "g012_spiess", 'mehrbenutzer' => "", 'betrGrp_ID' => 21, 'man_ID' => 18, 'notiz' => "" ],
            ['datumAdm' => "2017-11-10", 'titelAdm' =>"NULL", 'nameAdm' => "", 'vornameAdm' => "", 'emailAdm' => "", 'telefonAdm' => "", 'faxAdm' => "", 'mobiltelefonAdm' => "", 'benutzernameAdm' => "", 'nameMan' => "Henkedruck", 'holdingstruktur' => "", 'liegenschaften' => "", 'dbName' => "g013_henke", 'mehrbenutzer' => "", 'betrGrp_ID' => NULL, 'man_ID' => 19, 'notiz' => "" ],
            ['datumAdm' => "2020-11-19", 'titelAdm' =>"NULL", 'nameAdm' => "", 'vornameAdm' => "", 'emailAdm' => "", 'telefonAdm' => "", 'faxAdm' => "", 'mobiltelefonAdm' => "", 'benutzernameAdm' => "", 'nameMan' => "hpg plastics gmbh", 'holdingstruktur' => "", 'liegenschaften' => "", 'dbName' => "g014_hpg", 'mehrbenutzer' => "", 'betrGrp_ID' => 22, 'man_ID' => 20, 'notiz' => "" ],
            ['datumAdm' => "2018-03-13", 'titelAdm' =>"NULL", 'nameAdm' => "", 'vornameAdm' => "", 'emailAdm' => "", 'telefonAdm' => "", 'faxAdm' => "", 'mobiltelefonAdm' => "", 'benutzernameAdm' => "", 'nameMan' => "MB-DAH-Energy", 'holdingstruktur' => "", 'liegenschaften' => "", 'dbName' => "g015_mbdahenergy", 'mehrbenutzer' => "", 'betrGrp_ID' => 21, 'man_ID' => 21, 'notiz' => "" ],
            ['datumAdm' => "2018-08-09", 'titelAdm' =>"NULL", 'nameAdm' => "", 'vornameAdm' => "", 'emailAdm' => "", 'telefonAdm' => "", 'faxAdm' => "", 'mobiltelefonAdm' => "", 'benutzernameAdm' => "", 'nameMan' => "Alfried Krupp KH", 'holdingstruktur' => "", 'liegenschaften' => "", 'dbName' => "g016_alfKrupp", 'mehrbenutzer' => "", 'betrGrp_ID' => 22, 'man_ID' => 22, 'notiz' => "" ],
            ['datumAdm' => "2019-06-03", 'titelAdm' =>"NULL", 'nameAdm' => "", 'vornameAdm' => "", 'emailAdm' => "", 'telefonAdm' => "", 'faxAdm' => "", 'mobiltelefonAdm' => "", 'benutzernameAdm' => "", 'nameMan' => "EST-Edelstahl", 'holdingstruktur' => "", 'liegenschaften' => "", 'dbName' => "g015_eststahl", 'mehrbenutzer' => "", 'betrGrp_ID' => 21, 'man_ID' => 23, 'notiz' => "" ],
            ['datumAdm' => "2020-11-19", 'titelAdm' =>"NULL", 'nameAdm' => "", 'vornameAdm' => "", 'emailAdm' => "", 'telefonAdm' => "", 'faxAdm' => "", 'mobiltelefonAdm' => "", 'benutzernameAdm' => "", 'nameMan' => "InduRade", 'holdingstruktur' => "", 'liegenschaften' => "", 'dbName' => "g017_induRade", 'mehrbenutzer' => "", 'betrGrp_ID' => 22, 'man_ID' => 24, 'notiz' => "" ],
            ['datumAdm' => "2020-11-19", 'titelAdm' =>"NULL", 'nameAdm' => "", 'vornameAdm' => "", 'emailAdm' => "", 'telefonAdm' => "", 'faxAdm' => "", 'mobiltelefonAdm' => "", 'benutzernameAdm' => "", 'nameMan' => "ELB", 'holdingstruktur' => "", 'liegenschaften' => "", 'dbName' => "g018_elb", 'mehrbenutzer' => "", 'betrGrp_ID' => NULL, 'man_ID' => 25, 'notiz' => "" ],
            ['datumAdm' => "2020-12-14", 'titelAdm' =>"NULL", 'nameAdm' => "", 'vornameAdm' => "", 'emailAdm' => "", 'telefonAdm' => "", 'faxAdm' => "", 'mobiltelefonAdm' => "", 'benutzernameAdm' => "", 'nameMan' => "Huendgen Swisttal", 'holdingstruktur' => "", 'liegenschaften' => "", 'dbName' => "g019_huendSwist", 'mehrbenutzer' => "", 'betrGrp_ID' => NULL, 'man_ID' => 26, 'notiz' => "" ],
            ['datumAdm' => "2022-11-15", 'titelAdm' =>"NULL", 'nameAdm' => "", 'vornameAdm' => "", 'emailAdm' => "", 'telefonAdm' => "", 'faxAdm' => "", 'mobiltelefonAdm' => "", 'benutzernameAdm' => "", 'nameMan' => "psqlToSql", 'holdingstruktur' => "", 'liegenschaften' => "", 'dbName' => "psqlToSql", 'mehrbenutzer' => "", 'betrGrp_ID' => NULL, 'man_ID' => 27, 'notiz' => "" ],
            ['datumAdm' => "2022-11-15", 'titelAdm' =>"NULL", 'nameAdm' => "", 'vornameAdm' => "", 'emailAdm' => "", 'telefonAdm' => "", 'faxAdm' => "", 'mobiltelefonAdm' => "", 'benutzernameAdm' => "", 'nameMan' => "TestNewDatabase", 'holdingstruktur' => "", 'liegenschaften' => "", 'dbName' => "TestNewDatabase", 'mehrbenutzer' => "", 'betrGrp_ID' => NULL, 'man_ID' => 28, 'notiz' => "" ]
        ]);
    }
}
